version: "3.7"

services: 
    service:
        image: blockchain-experiment
        env_file: .env
        build: 
            target: builder
            context: .
        ports:
            - 18080:8080
        volumes: 
            - ./:/go/src/github.com/eduardohoraciosanto/blockchain-experiment
        command: gowatch